name: ubuntu

on:
  push:
    branches:
      - cmake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake .

      - name: Build
        run: make
