name: windows

on:
  push:
    branches:
      - cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install MinGW
      - name: Install MinGW
        run: |
          choco install mingw -y --no-progress
          refreshenv

      # Configure CMake and Build
      - name: Configure CMake and Build
        run: |
          cmake --build . --config Release
