name: windows

on:
  push:
    branches:
      - cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete CMake cache
        run: |
          rm -rf CMakeCache.txt CMakeFiles/

      - name: Configure CMake
        run: cmake .

      - name: Build
        run: cmake --build . --config Release

