name: windows

on:
  push:
    branches:
      - cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: egor-tensin/setup-mingw@v2

      - name: show dir
        run: ls

      - name: show dir
        run: pwd

      - name: Configure CMake
        run: cmake .

      - name: Build
        run: cmake --build .

